title: Longxiang's Blog Website
author: Longxiang Zhang
email: lz2869@columbia.edu
description: From Curiosity to Clarity

theme: minima

permalink: /:categories/:title/

navbar-links:
  Homepage: "https://lucas66zhang.github.io/PersonalBlog/"
  Categories: "https://lucas66zhang.github.io/PersonalBlog/categories/"
  Tags: "https://lucas66zhang.github.io/PersonalBlog/tags/"
  About me: "aboutme"
  Search: "search"
